### ISSUE TITLE
converting pytorch model to tensorflow 

### ISSUE THREAD

**Issue by Malathi15** [onnx/tutorials#134]
when i ran this command 
```
import onnx
from onnx_tf.backend import prepare

# Load the ONNX file
model = onnx.load('output/mnist.onnx')

# Import the ONNX model to Tensorflow
tf_rep = prepare(model)
```
I got the following error
```

AttributeError                            Traceback (most recent call last)
<ipython-input-38-86790127a780> in <module>()
      1 import onnx
----> 2 from onnx_tf.backend import prepare
      3 
      4 # Load the ONNX file
      5 model = onnx.load('output/mnist.onnx')

~\Desktop\onnx-tensorflow\onnx_tf\__init__.py in <module>()
----> 1 from . import frontend
      2 from . import backend

~\Desktop\onnx-tensorflow\onnx_tf\frontend.py in <module>()
     14 
     15 from onnx_tf.common import exception
---> 16 from onnx_tf.common.handler_helper import get_all_frontend_handlers
     17 from onnx_tf.common import IS_PYTHON3
     18 from onnx_tf.handlers.frontend_handler import FrontendHandler

~\Desktop\onnx-tensorflow\onnx_tf\common\handler_helper.py in <module>()
      3 from onnx import defs
 5 from onnx_tf.handlers.backend import *  # noqa
      6 from onnx_tf.handlers.backend_handler import BackendHandler
      7 from onnx_tf.handlers.frontend import *  # noqa

~\Desktop\onnx-tensorflow\onnx_tf\handlers\backend\is_inf.py in <module>()
      6 
      7 onnx_op("IsInf")
----> 8 tf_func(tf.math.is_inf)
      9 class IsInf(BackendHandler):
     10 

AttributeError: module 'tensorflow._api.v1.math' has no attribute 'is_inf'
```

Can anyone help me how to solve this issue ?

Thanks in advance

**Comment by pbashivan** [comment]
Same issue here. Any solutions?

**Comment by prasanthpul** [comment]
Please reopen if @pbashivan's solution doesn't work.

**Comment by chahna107** [comment]
@pbashivan I got the above mentioned error with Tensorflow 1.12.0. So I upgraded tensorflow to 1.14.0 as mentioned, but now I get a different error.

```
File "/usr/local/lib/python3.6/site-packages/onnx_tf/backend.py", line 55, in prepare
    return cls.onnx_model_to_tensorflow_rep(model, strict)
  File "/usr/local/lib/python3.6/site-packages/onnx_tf/backend.py", line 75, in onnx_model_to_tensorflow_rep
    return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
  File "/usr/local/lib/python3.6/site-packages/onnx_tf/backend.py", line 129, in _onnx_graph_to_tensorflow_rep
    onnx_node, tensor_dict, handlers, opset=opset, strict=strict)
  File "/usr/local/lib/python3.6/site-packages/onnx_tf/backend.py", line 224, in _onnx_node_to_tensorflow_op
    return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
  File "/usr/local/lib/python3.6/site-packages/onnx_tf/handlers/handler.py", line 59, in handle
    return ver_handle(node, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/onnx_tf/handlers/backend/lstm.py", line 212, in version_7
    return cls._common(node, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/onnx_tf/handlers/backend/lstm.py", line 182, in _common
    rnn_kwargs, tf_activations, direction)
  File "/usr/local/lib/python3.6/site-packages/onnx_tf/handlers/backend/rnn_mixin.py", line 33, in rnn
    cell_kwargs["activation"] = activations[1]
IndexError: list index out of range
```

Can you please help?
Thanks!

**Comment by M-crazy** [comment]
@chahna107 Hi, Have you solved the problem,I got the same error?

**Comment by chahna107** [comment]
@M-crazy Unfortunately no. I haven't found any solution to this yet.
