### ISSUE TITLE
ImportError: No module named 'tensorflow_addons'

### ISSUE THREAD

**Issue by wujiexiaowugui** [onnx/tutorials#201]
Traceback (most recent call last):
  File "pytorch2pb.py", line 31, in <module>
    from onnx_tf.backend import prepare
  File "/usr/local/lib/python3.5/dist-packages/onnx_tf/__init__.py", line 1, in <module>
    from . import backend
  File "/usr/local/lib/python3.5/dist-packages/onnx_tf/backend.py", line 29, in <module>
    from onnx_tf.common.handler_helper import get_all_backend_handlers
  File "/usr/local/lib/python3.5/dist-packages/onnx_tf/common/handler_helper.py", line 3, in <module>
    from onnx_tf.handlers.backend import *  # noqa
  File "/usr/local/lib/python3.5/dist-packages/onnx_tf/handlers/backend/hardmax.py", line 3, in <module>
    import tensorflow_addons as tfa
ImportError: No module named 'tensorflow_addons'

**Comment by askhade** [comment]
When did you encounter this issue? When you were trying a particular tutorial in this repo? If so which tutorial?
If not then please open this issue in the pytorch repo.

**Comment by rallen10** [comment]
I got this same error when trying to run the [OnnxTensorflowImport](https://github.com/onnx/tutorials/blob/master/tutorials/OnnxTensorflowImport.ipynb) tutorial. I worked around by installing with `pip install tensorflow-addons`

**Comment by yoosan** [comment]
> I got this same error when trying to run the [OnnxTensorflowImport](https://github.com/onnx/tutorials/blob/master/tutorials/OnnxTensorflowImport.ipynb) tutorial. I worked around by installing with `pip install tensorflow-addons`

wow, well done

**Comment by prasanthpul** [comment]
@chinhuang007 someone working on onnx-tf should take a look at the tutorial notebook linked above

**Comment by chinhuang007** [comment]
@prasanthpul Sure, will do.

**Comment by ztwater** [comment]
> I got this same error when trying to run the [OnnxTensorflowImport](https://github.com/onnx/tutorials/blob/master/tutorials/OnnxTensorflowImport.ipynb) tutorial. I worked around by installing with `pip install tensorflow-addons`

And remember to find a release match your tf version at [https://github.com/tensorflow/addons/releases](https://github.com/tensorflow/addons/releases).

**Comment by MaxRondelli** [comment]
> I got this same error when trying to run the [OnnxTensorflowImport](https://github.com/onnx/tutorials/blob/master/tutorials/OnnxTensorflowImport.ipynb) tutorial. I worked around by installing with `pip install tensorflow-addons`

While I try to install this library, I get the following error: 
`ERROR: Could not find a version that satisfies the requirement tensorflow-addons (from versions: none)
ERROR: No matching distribution found for tensorflow-addons`

even if I specify the latest version: 

`ERROR: Could not find a version that satisfies the requirement tensorflow-addons==0.23.0 (from versions: none) ERROR: No matching distribution found for tensorflow-addons==0.23.0`

Do you guys know how to solve this problem in order to conver ONNX model to TF format?

**Comment by AHMEDSANA** [comment]
I was experiencing an issue with `tensorflow_addons` due to a library version mismatch. To resolve this, I used the following command:

```bash
pip install 'keras<3.0.0' mediapipe-model-maker
```

This solution worked for me, and I recommend giving it a try, though I can't guarantee it will work for everyone.
