### ISSUE TITLE
onnx.onnx_cpp2py_export.checker.ValidationError: convolution_W in initializer but not in graph input

### ISSUE THREAD

**Issue by wonderzy** [onnx/tutorials#214]
convert from caffe model to tensorflow model
tensorflow version 2.1.0
onnx version 1.7.0

Successfully convert from caffe to coreml to onnx using [https://github.com/onnx/onnx-docker/blob/master/onnx-ecosystem/converter_scripts/caffe_coreml_onnx.ipynb](url)
When using [https://github.com/onnx/tutorials/blob/master/tutorials/OnnxTensorflowImport.ipynb](url), i got the error:
```
Traceback (most recent call last):
  File "convert_caffe2onnx2tf.py", line 36, in <module>
    tf_exp = prepare(onnx_model)  # prepare tf representation
  File "/data6/TF_quant/onnx-tensorflow/onnx_tf/backend.py", line 62, in prepare
    super(TensorflowBackend, cls).prepare(model, device, **kwargs)
  File "/data5/workshop/anaconda3/lib/python3.6/site-packages/onnx/backend/base.py", line 74, in prepare
    onnx.checker.check_model(model)
  File "/data5/workshop/anaconda3/lib/python3.6/site-packages/onnx/checker.py", line 93, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: convolution_W in initializer but not in graph input
```
Anything to resolve this?

**Comment by vinitra** [comment]
This looks like an error with the caffe2onnx exporter. We recommend asking in that repo directly as those developers are most familiar with the codebase.

One way to confirm that your conversion error is due to caffe2onnx and not the onnx2tf conversion step is to run the onnx checker directly and see that it fails.

```
model = onnx.load('model.onnx')
onnx.checker.check_model(model)
```

As a hack / workaround, you can edit the graph inputs directly using the [ONNX Python API](https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md) and specifically updating the [parts of the IR](https://github.com/onnx/onnx/blob/master/docs/IR.md#graphs) you want to change to include convolution_W as part of the graph inputs.

**Comment by maxalexger** [comment]
I have the exact same issue and am pretty confident this error can be fixed by installing different versions of packages. The project I am working on uses `mxnet` and the onnx conversions are working fine on several other machines. 

I think it has something to do with the version of protobuf (see this [issue](https://github.com/onnx/onnx/issues/932#issuecomment-388687601)), but I could not figure out which version to use yet.
