### ISSUE TITLE
Error exporting squeezenet in caffe2

### ISSUE THREAD

**Issue by amandeepsaini** [onnx/tutorials#25]
I followed the tutorial for exporting a caffe2 model (squeezenet) to ONNX, but got the error below:

> Traceback (most recent call last):
  File "caffe2toOnnx.py", line 24, in <module>
    value_info,
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/onnx/frontend.py", line 589, in caffe2_net_to_onnx_model
    model = make_model(cls.caffe2_net_to_onnx_graph(*args, **kwargs),
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/onnx/frontend.py", line 469, in caffe2_net_to_onnx_graph
    op, shapes=shapes))
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/onnx/frontend.py", line 384, in caffe2_op_to_onnx_node
    nodes = translator(op_def, shapes)
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/onnx/frontend.py", line 221, in _create_conv_pool_op
    assert not node.op_type.startswith("Global")
AssertionError

In addition, if I try to export googlenet instead, I get the following error:

  

>Traceback (most recent call last):
>     File "caffe2toOnnx.py", line 24, in
>     value_info,
>     File "/usr/local/lib/python2.7/dist-packages/caffe2/python/onnx/frontend.py", line 591, in caffe2_net_to_onnx_model
>     producer_name='onnx-caffe2', # producer name
>     File "/usr/local/lib/python2.7/dist-packages/onnx/helper.py", line 66, in make_model
>     setattr(model, k, v)
>     AttributeError: Assignment not allowed (no field "opset_imports" in protocol message object).

Any thoughts on what the problem may be?

**Comment by amandeepsaini** [comment]
Closing this issue, has been addressed in the onnx/onnx repository [#624 ](https://github.com/onnx/onnx/issues/624)
