### ISSUE TITLE
Exporting models from CNTK to ONNX works only for ResNet20(CIFAR10)

### ISSUE THREAD

**Issue by lukmaz** [onnx/tutorials#26]
Hello,
I tried the tutorial [Exporting models from CNTK to ONNX](https://github.com/onnx/tutorials/blob/master/tutorials/CntkOnnxExport.ipynb) on the [pretrained ResNet models](https://github.com/Microsoft/CNTK/blob/master/PretrainedModels/Image.md#resnet) and it works only for ResNet20 trained on CIFAR10. Not on ResNet110 trained on CIFAR10 nor on any model trained on ImageNet (including the models converted from Caffe2). 

Am I doing something wrong or the method actually does not work with different models? Here is the code and the output:

`convert.py`:
```
import cntk as C
model_path = "ResNet110_CIFAR10_CNTK.model"
z = C.Function.load(model_path)
z.save("model2.onnx", format=C.ModelFormat.ONNX)
```
```python convert.py 
Traceback (most recent call last):
  File "convert.py", line 5, in <module>
    z.save("model2.onnx", format=C.ModelFormat.ONNX)
  File "/opt/conda/envs/cntk/lib/python3.4/site-packages/cntk/internal/swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "/opt/conda/envs/cntk/lib/python3.4/site-packages/cntk/ops/functions.py", line 1504, in save
    return super(Function, self).save(filename, format.value)
  File "/opt/conda/envs/cntk/lib/python3.4/site-packages/cntk/cntk_py.py", line 2021, in save
    return _cntk_py.Function_save(self, *args)
RuntimeError: Node 'Combine: Output('ce', [], []), Output('errs', [], []), Output('top5Errs', [], []), Output('z', [#, ], [1000]) -> Output('ce', [], []), Output('errs', [], []), Output('top5Errs', [], []), Output('z', [#, ], [1000])': Unsupported node.

[CALL STACK]
[0x7f255d676899]                                                       + 0x857899
[0x7f255d892d61]    CNTK::CNTKToONNXHelper::  CreateNode  (std::shared_ptr<CNTK::Function> const&,  ONNXIR::Graph*,  std::unordered_map<std::shared_ptr<CNTK::Function>,ONNXIR::Node*,std::hash<std::shared_ptr<CNTK::Function>>,std::equal_to<std::shared_ptr<CNTK::Function>>,std::allocator<std::pair<std::shared_ptr<CNTK::Function> const,ONNXIR::Node*>>>&,  std::unordered_map<CNTK::Variable,ONNXIR::Node*,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,ONNXIR::Node*>>>&,  std::unordered_map<CNTK::Variable,CNTK::Variable,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,CNTK::Variable>>> const&) + 0x1461
[0x7f255d8930fb]    CNTK::CNTKToONNXHelper::  Copy  (std::shared_ptr<CNTK::Function> const&,  ONNXIR::Graph*) + 0x17b
[0x7f255d8933d5]    CNTK::CNTKToONNX::  CreateModel  (std::shared_ptr<CNTK::Function> const&) + 0x135
[0x7f255d8aa686]    CNTK::ONNXFormat::  Save  (std::shared_ptr<CNTK::Function> const&,  std::__cxx11::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>> const&) + 0x36
[0x7f255d67b64d]    CNTK::Function::  Save  (std::__cxx11::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>> const&,  CNTK::ModelFormat) + 0x3d
[0x7f255e2ffefb]                                                       + 0x1a3efb
[0x7f2580fb8d8e]    PyEval_EvalFrameEx                                 + 0x5ffe
[0x7f2580fbb371]    PyEval_EvalCodeEx                                  + 0x8b1
[0x7f2580fb9d2a]    PyEval_EvalFrameEx                                 + 0x6f9a
[0x7f2580fbb371]    PyEval_EvalCodeEx                                  + 0x8b1
[0x7f2580f19161]                                                       + 0x91161
[0x7f2580ee91f9]    PyObject_Call                                      + 0x59
[0x7f2580fb8766]    PyEval_EvalFrameEx                                 + 0x59d6
[0x7f2580fbb371]    PyEval_EvalCodeEx                                  + 0x8b1
[0x7f2580fb9d2a]    PyEval_EvalFrameEx                                 + 0x6f9a
[0x7f2580fbb371]    PyEval_EvalCodeEx                                  + 0x8b1
[0x7f2580fbb43b]    PyEval_EvalCode                                    + 0x3b
[0x7f2580fdbdb0]    PyRun_FileExFlags                                  + 0x130
[0x7f2580fdee44]    PyRun_SimpleFileExFlags                            + 0x104
[0x7f2580ff9276]    Py_Main                                            + 0xba6
[0x400acd]          main                                               + 0x15d
[0x7f25801b1830]    __libc_start_main                                  + 0xf0
[0x4008a9]```

**Comment by ebarsoum** [comment]
Hi @lukmaz,

Some of the model in CNTK have the training nodes part of the graph which isn't supported by ONNX. to convert such model to ONNX, you need to extract the inference graph as shown below:

import cntk as C

model_path = "ResNet110_CIFAR10_CNTK.model"
z = C.load_model(model_path)
zi = C.as_composite(z[0].owner)
zi.save("model2.onnx", format=C.ModelFormat.ONNX)

Thanks,
Emad

**Comment by lukmaz** [comment]
Thanks!
